[[plugins]]
repo = 'Shougo/neocomplete.vim'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'szw/vim-tags'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'vim-ruby/vim-ruby'

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'

[[plugins]]
repo = 'slim-template/vim-slim'

[[plugins]]
repo = 'tpope/vim-haml'
