[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'othree/yajs.vim'

