[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neocomplcache'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'othree/yajs.vim'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'
script_type = 'colors'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'google/vim-jsonnet'


