# Inserts ablank line between shell prompts
add_newline = false

format = '''
.-$time$username$hostname$directory $git_branch($git_state)$git_status $memory_usage $aws
`-\$ '''

scan_timeout = 10
[directory]
truncation_length = 100
fish_style_pwd_dir_length = 1
truncate_to_repo = false
format = "[$path]($style)[$read_only]($read_only_style)"

[conda]
disabled = true
format = ""

[python]
disabled = true

[time]
disabled = false
format = '[\[$time\]]($style)'
time_format = "%R"
style = "bold bright-red dimmed"

[git_branch]
format = "[$symbol$branch]($style)"
symbol = ""

# Replace the "❯" symbol in the prompt with "➜"
[character] # The name of the module we are configuring is "character"
success_symbol = "[➜](bold green)" # The "success_symbol" segment is being set to "➜" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[line_break]
disabled = false

[username]
show_always = true
format = "[$user]($style):"
style_user = "blue bold"
style_root = "black bold"

[docker_context]
format = "[$symbol$context]($style)"

[fill]
symbol = " "

[memory_usage]
disabled = false
threshold = -1
format = "($style)via $symbol[$ram]($style)"
style = 'bold green'

[hostname]
format = "[$hostname]($style)"
style = "bold dimmed green"

[aws]
format = 'on [ $symbol($profile)(\($region\) )]($style)'
style = 'bg:#F19E38 fg:black bold'
symbol = '🅰 '
[aws.region_aliases]
ap-southeast-2 = 'au'
us-east-1 = 'va'
ap-northeast-1 = 'apn-1'
