[tools]
"github:cli/cli" = "latest"
node = "lts"
ruby = "latest"
yarn = "1.22.19"
colima = "latest"
"github:hokaccha/givy" = "latest"
"github:sorah/mairu" = "latest"
"github:tokuhirom/mdroll" = "latest"

[settings]
github_attestations = false
idiomatic_version_file_enable_tools = ["node", "ruby"]
